language: node_js
node_js:
  - 10
addons:
  firefox: "63.0"
dist: xenial
services:
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
before_script:
  - npm install -g grunt-cli bower
  - bower install
script: npm test
